export const COLOR_SELECT = 'COLOR_SELECT';
export const TITLE_CHANGE = 'TITLE_CHANGE';
export const TEXT_CHANGE = 'TEXT_CHANGE';
export const DEVELOPER_CHANGE = 'DEVELOPER_CHANGE';
export const POST_NOTE = 'POST_NOTE';
export const GET_NOTES_LIST = 'GET_NOTES_LIST';
export const DELETE_NOTE = 'DELETE_NOTE';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const CHANGE_NOTE_STATUS = 'CHANGE_NOTE_STATUS';
export const GET_NOTE = 'GET_NOTE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST';
export const POST_PROJECT = 'POST_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const CHANGE_PROJECT_TITLE = 'CHANGE_PROJECT_TITLE';
export const SET_INITIAL_PROJECT = 'SET_INITIAL_PROJECT';
export const GET_USERS_LIST = 'GET_USERS_LIST';
export const SET_INITIAL_DEVELOPER = 'SET_INITIAL_DEVELOPER';
export const FILTER_BY_PROJECT = 'FILTER_BY_PROJECT';
export const FILTER_BY_DEVELOPER = 'FILTER_BY_DEVELOPER';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const NEW_COMMENT_CHANGE = 'NEW_COMMENT_CHANGE';
export const POST_COMMENT_TO_NOTE = 'POST_COMMENT_TO_NOTE';
export const TOGGLE_STATUS_SELECTION = 'TOGGLE_STATUS_SELECTION';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const POST_NOTE_CHANGES = 'POST_NOTE_CHANGES';
export const EDIT_ONE_COMMENT = 'EDIT_ONE_COMMENT';
export const COMMENT_EDITIONING = 'COMMENT_EDITIONING';
export const COMMENT_EDITED = 'COMMENT_EDITED';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_USER_LAST_NAME = 'CHANGE_USER_LAST_NAME';
export const CHANGE_USER_ROLE = 'CHANGE_USER_ROLE';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const CHANGE_REGISTER_NAME = 'CHANGE_REGISTER_NAME';
export const CHANGE_REGISTER_LAST_NAME = 'CHANGE_REGISTER_LAST_NAME';
export const CHANGE_REGISTER_PASSWORD = 'CHANGE_REGISTER_PASSWORD';
export const CHANGE_REGISTER_EMAIL = 'CHANGE_REGISTER_EMAIL';
export const REGISTER = 'REGISTER';




